[package]
name = "relay"
version = "0.1.0"
edition = "2021"

[dependencies]
ws = "0.9.2"
mio = "0.8"
uuid = { version = "1.3.2", features = ["v4"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }