[package]
name = "relay"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-util = "0.3"
tokio-tungstenite = "0.18.0"
tokio = { version = "1.28.1", features = ["full"] }
serde_json = "1.0"
dashmap = "5.4.0"
