name: Build and Test

on:
  push:
    branches: ["master"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      rust:
        image: rust:latest
        ports:
        - 3012:3012
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
        
      - name: Build
        run: cargo build --release

      - name: Test
        run: cargo test