name: Build, Test and Publish

on:
  push:
    branches: ["master"]
    tags:
      - '*'

jobs:
  build-test-publish:
    permissions: write-all
    name: Build, Test and Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: relay
            asset_name: relay-linux-amd64
          - os: windows-latest
            artifact_name: relay
            asset_name: relay-windows-amd64.exe
          - os: macos-latest
            artifact_name: relay
            asset_name: relay-macos-amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
        
      - name: Build
        run: cargo build --release

      - name: Test
        run: cargo test
      
      - name: Publish
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}